name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Cache SwiftPM dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build (unsigned)
        run: |
          set -o pipefail
          xcodebuild \
            -scheme FloorPlanPro \
            -destination "generic/platform=iOS" \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            build | xcpretty

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: ~/Library/Developer/Xcode/DerivedData/**/Logs

  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run SwiftLint if available
        run: |
          if command -v swiftlint >/dev/null 2>&1; then
            swiftlint
          else
            echo "SwiftLint not installed — skipping"
          fi

      - name: Run SwiftFormat if available
        run: |
          if command -v swiftformat >/dev/null 2>&1; then
            swiftformat .
          else
            echo "SwiftFormat not installed — skipping"
          fi
